# Generated by Django 3.2.14 on 2022-08-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cards", "0008_auto_20220729_2340"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ammount",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "cold_waste",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        verbose_name="Холодный отход",
                    ),
                ),
                (
                    "hot_waste",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        verbose_name="Горячий отход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="techcard",
            options={
                "ordering": ["-modified_date"],
                "verbose_name": "Техкарта",
                "verbose_name_plural": "Техкарты",
            },
        ),
        migrations.AddField(
            model_name="techcard",
            name="modified_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата изменения"
            ),
        ),
        migrations.AddField(
            model_name="techcard",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                max_digits=8,
                verbose_name="Вес",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="cards.Tag",
                verbose_name="Тэги",
            ),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="create_date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата изменения"
            ),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="is_semifabricate",
            field=models.BooleanField(
                default=False, verbose_name="Это полуфабрикат"
            ),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="techcards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="semifabricate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.product",
                verbose_name="Полуфабрикат",
            ),
        ),
        migrations.DeleteModel(
            name="Ingridient",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="techcard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.techcard",
                verbose_name="Техкарта",
            ),
        ),
        migrations.AddField(
            model_name="techcard",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="techcards",
                through="cards.Ingredient",
                to="cards.Product",
                verbose_name="Ингредиенты",
            ),
        ),
    ]
