# Generated by Django 3.2.14 on 2022-08-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20220801_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='techcard',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='cards.Tag', verbose_name='Тэги'),
        ),
    ]
